version: "3.7"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    deploy:
      replicas: 2
    volumes:
      - ${VOLUMES_BASE_DIR}/pets-comments:/opt/data
    networks:
      pets-network:
        aliases:
          - pets-comments

networks:
  pets-network:
    external: true
