apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
        - name: ${SERVICE}
          image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /opt/data
              name: comments-volume
      volumes:
        - name: comments-volume
          hostPath:
            path: ${VOLUMES_BASE_DIR}/pets-comments
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  ports:
    - name: pod-port
      protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: ${SERVICE}
