version: "3.7"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    networks:
      pets-network:
        aliases:
          - pets-web-vue

networks:
  pets-network:
    external: true
