apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE}
  template:
    metadata:
      labels:
        app: ${SERVICE}
    spec:
      containers:
        - name: ${SERVICE}
          image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${SERVICE}:${SERVICE_VERSION}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  labels:
    app: ${SERVICE}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: ${SERVICE}
