apiVersion: v1
kind: Service
metadata:
  name: pets-network
spec:
  selector:
    name: pets
  clusterIP: None
  ports:
    - name: pets # Actually, no port is needed.
      port: 1234
      targetPort: 1234
