version: "3"

services:
  server:
    build: .
    image: ${DOCKER_REGISTRY}/${ORGANIZATION}/${SERVICE}:${SERVICE_VERSION}
    ports:
      - 80
    deploy:
      replicas: 2
    networks:
      pets-network:
        aliases:
         - pets-turtles

networks:
  pets-network:
    external: true
